version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proyecto-2025-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proyecto-2025-backend
    ports:
      - "3000:3000" 
    depends_on:
      - captioning
      - tts
    environment:
      - JWT_SECRET=supersecret
      - CAPTION_API_URL=http://captioning:3000/caption
      - TTS_API_URL=http://tts:8002/tts
      - PUBLIC_TTS_HOST=localhost
    volumes:
      - ./data:/app/data
    

  captioning:
    build:
      context: ./captioning
      dockerfile: Dockerfile
    container_name: proyecto-2025-captioning
    ports:
      - "3001:3000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./captioning/outputs:/app/outputs
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    
  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile
    container_name: proyecto-2025-tts
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tts/outputs:/app/outputs
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload

  speech-to-text:
    build: ./SpeechToText
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5000
      - MODEL_PATH=/app/whisper_argentino
    volumes:
      - ./SpeechToText:/app
      - ./SpeechToText/speech-to-text-andreani/whisper_argentino:/app/whisper_argentino
    networks:
      - app-network